# Generated by Django 4.0.6 on 2022-07-24 12:54

import apps.clients.models
from django.db import migrations, models
import mirage.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=150)),
                ('fec_birthday', models.DateField()),
                ('codigo_zip', models.IntegerField()),
                ('ip', models.IntegerField()),
                ('direccion', models.CharField(max_length=250)),
                ('geo_latitud', models.FloatField()),
                ('geo_longitud', models.FloatField()),
                ('color_favorito', models.CharField(max_length=100)),
                ('auto', models.CharField(max_length=250)),
                ('auto_modelo', models.CharField(max_length=250)),
                ('auto_tipo', models.CharField(max_length=250)),
                ('auto_color', models.CharField(max_length=250)),
                ('cantidad_compras_realizadas', models.IntegerField(default=0)),
                ('credit_card_num', mirage.fields.EncryptedIntegerField(max_length=64)),
                ('credit_card_ccv', mirage.fields.EncryptedIntegerField(max_length=64)),
                ('cuenta_numero', models.IntegerField()),
                ('fec_alta', models.DateTimeField(auto_now_add=True)),
                ('foto_dni', models.ImageField(blank=True, upload_to=apps.clients.models.upload_to)),
                ('avatar', models.ImageField(blank=True, upload_to=apps.clients.models.upload_to)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['fec_alta'],
            },
        ),
    ]
