# Generated by Django 4.0.6 on 2022-07-24 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_cliente_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='credit_card_ccv',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='credit_card_num',
        ),
    ]
