# Generated by Django 4.0.6 on 2022-07-24 13:19

from django.db import migrations
import mirage.fields


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_cliente_credit_card_ccv_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='credit_card_ccv',
            field=mirage.fields.EncryptedCharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cliente',
            name='credit_card_num',
            field=mirage.fields.EncryptedCharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
