# Generated by Django 4.0.6 on 2022-07-24 15:16

import apps.clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_cliente_credit_card_ccv_cliente_credit_card_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=apps.clients.models.upload_to),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fec_alta',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='foto_dni',
            field=models.ImageField(blank=True, null=True, upload_to=apps.clients.models.upload_to),
        ),
    ]
