# Generated by Django 4.0.6 on 2022-07-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0005_alter_cliente_avatar_alter_cliente_fec_alta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fec_birthday',
            field=models.DateTimeField(),
        ),
    ]
